- type: job
  id: HospitalityDirector
  name: job-name-hd
  description: job-description-hd
  playTimeTracker: JobHospitalityDirector
  requirements:
  - !type:DepartmentTimeRequirement
    department: Service
    time: 10h
  #weight: 20 # Funky - Weighting all jobs equally now
  startingGear: HDGear
  icon: "JobIconHospitalityDirector"
  joinNotifyCrew: true
  supervisors: job-supervisors-captain
  access:
  - Command
  - HospitalityDirector
  - Bar
  - Service
  - Maintenance
  - Janitor
  - Theatre
  - Kitchen
  - Chapel
  - Library
  special:
  #- !type:AddImplantSpecial
  #  implants: [ MindShieldImplant ] # Removed mindshields
  - !type:AddComponentSpecial
    components:
    - type: CommandStaff

- type: startingGear
  id: HDGear
  equipment:
    head: ClothingHeadHatTophat
    shoes: ClothingShoesColorBlack
    id: HDPDA
    ears: ClothingHeadsetHD

- type: chameleonOutfit
  id: HDChameleonOutfit
  job: HospitalityDirector
  hasMindShield: true
  equipment:
    eyes: ClothingEyesHudBeer
    mask: ClothingMaskNeckGaiter
    neck: ClothingNeckScarfStripedGreen
    outerClothing: ClothingOuterWinterColorGreen
