using Content.Shared._Funkystation.StationTime.Components;
using Content.Shared._Funkystation.StationTime.EntitySystems;
using Content.Shared.CCVar;
using Content.Shared.Station;
using Content.Shared.TextScreen;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;
using Robust.Shared.Utility;

namespace Content.Client.Communications.UI.Widgets;

/// <summary>
/// A set of controls to send out announcements or broadcast messages to screens.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class MessagingControls : TabContainer
{
    [Dependency] private IConfigurationManager _cfg = default!;
    [Dependency] private IEntityManager _entMan = default!;
    [Dependency] private IGameTiming _timing = default!;


    private StationTimeSystem _stationTime; // Funky Change
    private SharedStationSystem _station; // Funky Change
    private SharedAppearanceSystem _appearance;
    private readonly string[] _lineEndings = new[] { "\r\n", "\n" };
    private const int MaxScreenCharacters = 32;

    // Entity temporarily created to display a screen preview
    private EntityUid _broadcastDisplayEntity = EntityUid.Invalid;
    private TimeSpan? _screenTextTime = null;

    public event Action<string>? OnRadioAnnounce;
    public event Action<string>? OnScreenBroadcast;

    private bool _canRadioAnnounce;
    public bool CanRadioAnnounce
    {
        set
        {
            _canRadioAnnounce = value;
            SyncButtonState();
        }
    }

    private bool _canScreenBroadcast;
    public bool CanScreenBroadcast
    {
        set
        {
            _canScreenBroadcast = value;
            SyncButtonState();
        }
    }

    public MessagingControls()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        RadioMessageInput.Placeholder = new Rope.Leaf(Loc.GetString("comms-console-menu-announcement-placeholder"));
        RadioMessageInput.OnTextChanged += (_) => SyncButtonState();

        AnnounceButton.OnPressed += _ =>
        {
            OnRadioAnnounce?.Invoke(Rope.Collapse(RadioMessageInput.TextRope));
        };

        _appearance = _entMan.System<SharedAppearanceSystem>();
        _stationTime = _entMan.System<StationTimeSystem>(); //Funky change
        _station = _entMan.System<SharedStationSystem>(); //Funky change

        ScreenMessageInput.Placeholder = new Rope.Leaf(Loc.GetString("comms-console-menu-broadcast-placeholder"));
        ScreenMessageInput.OnTextChanged += _ => UpdateScreenText();

        BroadcastButton.OnPressed += _ =>
        {
            var strings = GetScreenStringArray();
            OnScreenBroadcast?.Invoke(GetScreenString(strings));
        };

        SyncButtonState();
        UpdateScreenText();
    }

    public void SetBroadcastDisplayEntity(EntProtoId broadcastEntityId)
    {
        _broadcastDisplayEntity = _entMan.Spawn(broadcastEntityId);

        if (_broadcastDisplayEntity.IsValid())
            BroadcastEntityDisplay.SetEntity(_broadcastDisplayEntity);
    }

    protected override void ExitedTree()
    {
        if (_broadcastDisplayEntity.IsValid())
            _entMan.DeleteEntity(_broadcastDisplayEntity);
    }

    private void SyncButtonState()
    {
        var maxAnnounceLength = _cfg.GetCVar(CCVars.ChatMaxAnnouncementLength);
        if (_canRadioAnnounce)
        {
            if (RadioMessageInput.TextLength > maxAnnounceLength)
            {
                AnnounceButton.Disabled = true;
                AnnounceButton.ToolTip = Loc.GetString("comms-console-message-too-long");
            }
            else
            {
                AnnounceButton.Disabled = false;
                AnnounceButton.ToolTip = Loc.GetString("comms-console-menu-announcement-button-tooltip");
            }
        }
        else
        {
            AnnounceButton.Disabled = true;
            AnnounceButton.ToolTip = Loc.GetString("comms-console-message-cannot-send");
        }

        UpdateCharacterLimitLabel(AnnounceCharLimitLabel, RadioMessageInput.TextLength, maxAnnounceLength);

        BroadcastButton.Disabled = !_canScreenBroadcast;
    }

    private void UpdateScreenText()
    {
        var strings = GetScreenStringArray();

        var topCount = strings.Length > 0 ? strings[0].Length : 0;
        var bottomCount = strings.Length > 1 ? strings[1].Length : 0;

        UpdateCharacterLimitLabel(BroadcastTopCharLimitLabel, topCount, MaxScreenCharacters);
        UpdateCharacterLimitLabel(BroadcastBottomCharLimitLabel, bottomCount, MaxScreenCharacters);

        if (!_broadcastDisplayEntity.IsValid())
            return;

        // Funky Change Start

        var station = _station.GetOwningStation(_broadcastDisplayEntity);
        if (station != null && _entMan.TryGetComponent<StationTimeComponent>(station.Value, out var timeComp))
        {
            var st = _stationTime.GetStationTime((station.Value, timeComp));
            _screenTextTime ??= st.TimeOfDay; // Funky Change
        }
        else
        {
            _screenTextTime ??= _timing.CurTime;
        }

        // Funky Change End

        _appearance.SetData(_broadcastDisplayEntity, TextScreenVisuals.ScreenText, GetScreenString(strings));
        _appearance.SetData(_broadcastDisplayEntity, TextScreenVisuals.ScreenTextTime, _screenTextTime.Value);
    }

    /// <summary>
    /// Updates <paramref name="label"/> based on the given <paramref name="length"/> and <paramref name="maximum"/>.
    /// </summary>
    private void UpdateCharacterLimitLabel(Label label, int length, int maximum)
    {
        string styleClass = length > maximum
            ? CommunicationsConsoleSheetlet.CharLimitExceeded
            : CommunicationsConsoleSheetlet.CharLimit;
        label.SetOnlyStyleClass(styleClass);
        label.Text = Loc.GetString("comms-console-char-limit",
            ("count", length),
            ("max", maximum));
    }

    /// <summary>
    /// Returns a string array with the un-sanitized top (and possibly bottom) messages
    /// </summary>
    private string[] GetScreenStringArray()
    {
        return Rope.Collapse(ScreenMessageInput.TextRope).Split(_lineEndings, StringSplitOptions.None);
    }

    /// <summary>
    /// Transforms an array from <see cref="GetScreenStringArray"/> into a string suitable for AppearanceData or net messages.
    /// </summary>
    private string GetScreenString(string[] strings)
    {
        return GetStringAtIndex(strings, 0) + "\n" + GetStringAtIndex(strings, 1);
    }

    /// <summary>
    /// Retrieves and limits a string from <paramref name="strings"/> at <paramref name="index"/>,
    /// limiting it to the number of characters that can sent to a screen.
    /// </summary>
    private string GetStringAtIndex(string[] strings, int index)
    {
        if (strings.Length > index && strings[index].Length > 0)
            return strings[index].Substring(0, int.Min(MaxScreenCharacters, strings[index].Length));
        else
            return "";
    }
}
